version: '3'

services:
  project-db:
    image: postgres:15
    restart: always
    env_file:
      - Source/credentials/.env
    environment:
      - POSTGRES_PASSWORD=$/{POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - project-db-data:/var/lib/postgresql/data

  project-app:
    image: notexists/kaggle-data-download-app:1.0
#    volumes:
#      - .:/app
    env_file:
      - Source/credentials/.env
    environment:
      - PG_USERNAME=$/{PGUSER}
      - PG_PASSWORD=$/{PGPASSWORD}
      - PG_HOST=$/{PGHOST}
      - PG_PORT=$/{PGPORT}
      - PG_DATABASE_NAME=$/{PGDATABASE}

volumes:
  project-db-data:
    driver: local