version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  project-db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 20s
      retries: 5
    volumes:
      - project-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  project-app:
    #build:
      #context: .
      #dockerfile: Dockerfile
    image: notexists/kaggle-data-download-app:1.0
    depends_on:
      project-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}

volumes:
  project-db-data:
    driver: local