name:

version: '3'

services:
  project-db:
    image: postgres:15
    ports:
      - 5432:5432

  project-app:
    image:
    env_file:
      - Source/credentials/.env
    environment:
      - PG_USERNAME=${PGUSER}
      - PG_PASSWORD=${PGPASSWORD}
      - PG_HOST=${PGHOST}
      - PG_PORT=${PGPORT}
      - PG_DATABASE_NAME=${PGDATABASE}
