version: '3'

services:
  project-db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - Source/credentials/.env
    environment:
      - POSTGRES_USER=$/{POSTGRES_USER}
      - POSTGRES_PASSWORD=$/{POSTGRES_PASSWORD}
      - POSTGRES_DB=kaggle-data-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 15s
      retries: 5
    volumes:
      - project-db-data:/var/lib/postgresql/data

  project-app:
    image: notexists/kaggle-data-download-app:1.0
    depends_on:
      project-db:
        condition: service_healthy
    #    volumes:
    #      - .:/app
    env_file:
      - Source/credentials/.env
    environment:
      - PGUSER=$/{PGUSER}
      - PGPASSWORD=$/{PGPASSWORD}
      - PGHOST=$/{PGHOST}
      - PGPORT=5432
      - PGDATABASE=$/{PGDATABASE}
      - KAGGLE_USERNAME=$/{KAGGLE_USERNAME}
      - KAGGLE_KEY=$/{KAGGLE_KEY}

volumes:
  project-db-data:
    driver: local